# 工作流名称
name: Sync Upstream Fork

# 触发器配置
on:
  # 允许在 Actions 页面手动触发此工作流
  workflow_dispatch:

  # 定时任务：使用 cron 语法
  # 此处设置为每周一的 02:00 UTC 时间，约等于北京时间上午10点
  schedule:
    - cron: '0 2 * * 1'

# 任务配置
jobs:
  sync:
    # 运行环境
    runs-on: ubuntu-latest

    # 为此任务授予权限，允许它写入仓库内容（即 git push）
    permissions:
      contents: write

    # 步骤
    steps:
      # 第一步：检出（Checkout）你自己的仓库
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          # persist-credentials: false 是为了下一步能使用 GITHUB_TOKEN
          # fetch-depth: 0 是为了获取所有历史记录，以便进行合并
          persist-credentials: false
          fetch-depth: 0

      # 第二步：执行同步脚本
      - name: Sync with Upstream
        run: |
          # 配置 Git 用户信息，让提交记录显示为由 actions-bot 操作
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # 添加上游（upstream）仓库的远程地址
          git remote add upstream https://github.com/XIU2/CloudflareSpeedTest.git
          
          # 从上游仓库获取所有分支和标签
          git fetch upstream
          
          echo "Current branch is $(git rev-parse --abbrev-ref HEAD)"
          echo "Merging from upstream/master..."

          # 切换到你的主分支（通常是 main 或 master）
          # 如果你的主分支是 master，请将下面的 "main" 改为 "master"
          git checkout master
          
          # 合并上游仓库的主分支到你的主分支
          # 如果上游主分支是 master，请将 "upstream/main" 改为 "upstream/master"
          git merge upstream/master --no-edit
          
          # 将合并后的代码推送到你自己的仓库（origin）
          git push origin master
